
[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11"

[[constraint]]
  name = "k8s.io/client-go"
  version = "8.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true
